name: CI/CD with Approval Workflow

on:
 workflow_dispatch
# dsd
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: main
      url: https://example.com  

    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Comando para o deploy (ex. usando `gcloud`, `aws`, etc)
          echo "Deployment successful!"
